apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-portal
  labels:
    app: vault-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-portal
  template:
    metadata:
      labels:
        app: vault-portal
    spec:
      containers:
        - name: vault-portal
          image: robadrinacr1.azurecr.io/vault-portal:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: VITE_AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: vault-portal-configmap
                  key: auth-service-url
---
apiVersion: v1
kind: Service
metadata:
  name: vault-portal-service
spec:
  selector:
    app: vault-portal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
