apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-authservice-configmap
data:
  server_port: '3000'
  portal_url: 'https://friendvault.netlify.app'
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-authservice-secret
type: Opaque
data:
  jwt_secret: ZnJpZW5kVmF1bHRTZWNyZXRKV1RDb2Rl
  database_url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnJvaGl0aEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZnJpZW5kdmF1bHQ=
  connection_string: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXJvYmFkcmluc2ExO0FjY291bnRLZXk9WXFBWFlTSFZHRFMxaFR5NERKNWRvTENwU3J0Z3FBOFRocWJhNlRkSVVFQ0pqL0pzYTg1REQzeWM5bnlSdm42RXhPVFhIcWZOdU0vU1ZkMDBEMGRGeXc9PTtFbmRwb2ludFN1ZmZpeD1jb3JlLndpbmRvd3MubmV0
  container: ZnJpZW5kdmF1bHQ=
  sas: c3A9cmFjd2RsJnN0PTIwMjMtMTItMTZUMTA6MjM6MjNaJnNlPTIwMjMtMTItMzFUMTg6MjM6MjNaJnNwcj1odHRwcyZzdj0yMDIyLTExLTAyJnNyPWMmc2lnPTNOdFZsUmgwRjhKUTR3V1Y0U1l5SVBaZGJWcVRLMG5xSDJlVjdvbXglMkZ3byUzRA==
